src/Senior.Revenda.Mvc/Controllers/BaseController.cs
using Senior.Revenda.Contract.Applications;
using System.Web.Mvc;

namespace Senior.Revenda.Mvc.Controllers
{
    public class BaseController : Controller
    {
        protected IEnderecoApplication _enderecoApplication;

        [HttpGet]
        public JsonResult GetByCep(string cep)
        {
            var result = _enderecoApplication.GetByCep(cep);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

src/Senior.Revenda.Mvc/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Senior.Revenda.Mvc.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/Senior.Revenda.Mvc/Controllers/MarcaController.cs
using Senior.Revenda.Contract.Applications;
using Senior.Revenda.Contract.DTOs;
using Senior.Revenda.Contract.DTOs.Filter;
using System;
using System.Web.Mvc;

namespace Senior.Revenda.Mvc.Controllers
{
    public class MarcaController : BaseController
    {
        private readonly IMarcaApplication _marcaApplication;

        public MarcaController(IMarcaApplication marcaApplication)
        {
            _marcaApplication = marcaApplication;
        }

        public ActionResult Index()
        {
            return View(new MarcaFilterDTO());
        }

        public ActionResult Cadastrar()
        {
            return View(new MarcaDTO());
        }

        [HttpGet]
        public ActionResult Consultar(MarcaFilterDTO filtro)
        {
            var result = _marcaApplication.GetByFilter(filtro);
            return View("Index", result);
        }

        [HttpPost]
        public ActionResult Cadastrar(MarcaDTO viewModel)
        {
            _marcaApplication.Create(viewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult Cancelar(Guid id)
        {
            _marcaApplication.Cancelar(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Ativar(Guid id)
        {
            _marcaApplication.Ativar(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

src/Senior.Revenda.Mvc/Controllers/ProprietarioController.cs
using Senior.Revenda.Contract.Applications;
using Senior.Revenda.Contract.DTOs;
using Senior.Revenda.Contract.DTOs.Filter;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Senior.Revenda.Mvc.Controllers
{
    public class ProprietarioController : BaseController
    {
        private readonly IProprietarioApplication _proprietarioApplication;
        private readonly IEstadoApplication _estadoApplication;

        public ProprietarioController(IProprietarioApplication proprietarioApplication
            , IEnderecoApplication enderecoApplication
            , IEstadoApplication estadoApplication)
        {
            _proprietarioApplication = proprietarioApplication;
            _estadoApplication = estadoApplication;
            _enderecoApplication = enderecoApplication;
        }

        public ActionResult Index()
        {
            return View(new ProprietarioFilterDTO());
        }

        public ActionResult Cadastrar()
        {
            GetViewBag();
            return View(new ProprietarioDTO());
        }

        public ActionResult Alterar(Guid id)
        {
            var result = _proprietarioApplication.Get(id);
            GetViewBag();
            return View(result);
        }

        [HttpGet]
        public ActionResult Consultar(ProprietarioFilterDTO filtro)
        {
            var result = _proprietarioApplication.GetByFilter(filtro);
            return View("Index", result);
        }

        [HttpPost]
        public ActionResult Cadastrar(ProprietarioDTO viewModel)
        {
            _proprietarioApplication.Create(viewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Alterar(ProprietarioDTO viewModel)
        {
            _proprietarioApplication.Update(viewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult Cancelar(Guid id)
        {
            _proprietarioApplication.Cancelar(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Ativar(Guid id)
        {
            _proprietarioApplication.Ativar(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        private void GetViewBag()
        {
            var estados = _estadoApplication.GetAllAtivos();

            ViewBag.Estado = new SelectList(estados, "Id", "UF");
        }
    }
}

src/Senior.Revenda.Mvc/Controllers/VeiculoController.cs
using Senior.Revenda.Contract.Applications;
using Senior.Revenda.Contract.DTOs;
using Senior.Revenda.Contract.DTOs.Filter;
using System;
using System.Web.Mvc;

namespace Senior.Revenda.Mvc.Controllers
{
    public class VeiculoController : BaseController
    {

        private readonly IVeiculoApplication _veiculoApplication;
        private readonly IMarcaApplication _marcaApplication;
        private readonly IProprietarioApplication _proprietarioApplication;

        public VeiculoController(IVeiculoApplication veiculoApplication
            , IMarcaApplication marcaApplication
            , IProprietarioApplication proprietarioApplication)
        {
            _veiculoApplication = veiculoApplication;
            _marcaApplication = marcaApplication;
            _proprietarioApplication = proprietarioApplication;
        }

        public ActionResult Index()
        {
            GetViewBag();
            return View(new VeiculoFilterDTO());
        }

        public ActionResult Cadastrar()
        {
            GetViewBag();
            return View(new VeiculoDTO());
        }

        public ActionResult Alterar(Guid id)
        {
            var result = _veiculoApplication.Get(id);
            GetViewBag();
            return View(result);
        }

        [HttpGet]
        public ActionResult Consultar(VeiculoFilterDTO filtro)
        {
            var result = _veiculoApplication.GetByFilter(filtro);
            GetViewBag();
            return View("Index", result);
        }

        [HttpPost]
        public ActionResult Cadastrar(VeiculoDTO viewModel)
        {
            _veiculoApplication.Create(viewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Alterar(VeiculoDTO viewModel)
        {
            _veiculoApplication.Update(viewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult Vender(Guid id)
        {
            _veiculoApplication.Vendido(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Indisponibilizar(Guid id)
        {
            _veiculoApplication.Indisponivel(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        private void GetViewBag()
        {
            var marcas = _marcaApplication.GetAllAtivos();

            ViewBag.Marca = new SelectList(marcas, "Id", "Nome");

            var proprietarios = _proprietarioApplication.GetAllAtivos();

            ViewBag.Proprietario = new SelectList(proprietarios, "Id", "Nome");
        }
    }
}

src/Senior.Revenda.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/Senior.Revenda.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Senior.Revenda.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Revenda";
}

<div class="row">
    <h1>Revenda</h1>
    <p>Aplicação de revenda.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Marcas</h2>
        <p>Marcas de veículos automotivos</p>
        @Html.ActionLink("Marca", "Index", "Marca")
    </div>
    <div class="col-md-4">
        <h2>Proprietários</h2>
        <p>Proprietário de veículos automotivos</p>
        @Html.ActionLink("Prorietário", "Index", "Proprietario")
    </div>
    <div class="col-md-4">
        <h2>Veículo</h2>
        <p>Veículos automotivos</p>
        @Html.ActionLink("Veículo", "Index", "Veiculo")
    </div>
</div>

src/Senior.Revenda.Mvc/Views/Marca/Cadastrar.cshtml
@model Senior.Revenda.Contract.DTOs.MarcaDTO
@{
    ViewBag.Title = "Cadastrar - Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Marca <small>Cadastro</small></h3>
    </div>
    <div class="panel-body">
        <form action="Cadastrar" method="post">
            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Nome, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Nome, new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12">
                <hr />
            </div>

            <div class="col-md-offset-10">
                <input type="button" class="btn btn-primary" onclick="Back()" value="Cancelar" />
                <input type="submit" class="btn btn-success" value="Cadastrar" />
            </div>
        </form>
    </div>
</div>

<script src="~/TypeScripts/GlobalScript.js"></script>

src/Senior.Revenda.Mvc/Views/Marca/Index.cshtml
@model Senior.Revenda.Contract.DTOs.Filter.MarcaFilterDTO

@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Marca <small>Consulta</small></h3>
    </div>
    <div class="panel-body">
        <div class="col-md-6">
            @Html.ActionLink("Cadastrar", "Cadastrar", "Marca")
        </div>

        <div class="col-md-12">
            <hr />
        </div>

        <form action="@Url.Content("~/Marca/Consultar")" method="get">
            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.Nome, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.Nome, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6">
                @Html.LabelFor(m => m.Status, new { @class = "col-md-3" })
                <div class="col-md-9">
                    @foreach (var value in Enum.GetValues(Model.Status.GetType()))
                    {
                        <div form-check form-check-inline">
                            @Html.RadioButtonFor(m => m.Status, value, new { @class = "form-check-input" })
                            @Html.Label(value.ToString(), new { @class = "form-check-label" })
                        </div>
                    }
                </div>
            </div>

            <div class="col-md-12">
                <hr />
            </div>

            <div class="col-md-offset-10">
               <input type="submit" class="btn btn-primary" value="Consultar" />
            </div>
        </form>

        @Html.Partial("_ConsultaMarca", Model)
    </div>
</div>

<script src="~/TypeScripts/Marca/Index.js"></script>

src/Senior.Revenda.Mvc/Views/Marca/_ConsultaMarca.cshtml
@model Senior.Revenda.Contract.DTOs.Filter.MarcaFilterDTO
@using Senior.Revenda.Contract.Enum 

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Lista.Count() > 0)
        {
            foreach (var item in Model.Lista)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @if (item.Status == StatusEnum.Ativo)
                        {
                            <a onclick="CancelarMarca('@Request.Url.Authority', '@item.Id')">Cancelar</a>
                        }
                        else
                        {
                            <a onclick="AtivarMarca('@Request.Url.Authority', '@item.Id')">Ativar</a>
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3">Nenhum registro encontrado.</td>
            </tr>
        }
    </tbody>
</table>

src/Senior.Revenda.Mvc/Views/Proprietario/Alterar.cshtml
@model Senior.Revenda.Contract.DTOs.ProprietarioDTO
@{
    ViewBag.Title = "Alterar - Proprietário";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Proprietário <small>Alteração</small></h3>
    </div>
    <div class="panel-body">
        <form action="Alterar" method="post">
            @Html.HiddenFor(m => m.Id)
            <input hidden id="url" value="@Request.Url.Authority" />

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Nome, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Nome, new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Documento, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Documento, new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Endereco.Cep, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Endereco.Cep, new { @class = "form-control col-md-10", @onchange = "onChangeCep()" })
            </div>

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Endereco.Logradouro, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Endereco.Logradouro, new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Endereco.Numero, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Endereco.Numero, new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Endereco.Bairro, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Endereco.Bairro, new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Endereco.Cidade, new { @class = "col-md-2" })
                @Html.TextBoxFor(m => m.Endereco.Cidade, new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12 form-group">
                @Html.LabelFor(m => m.Endereco.IdEstado, new { @class = "col-md-2" })
                @Html.DropDownListFor(m => m.Endereco.IdEstado, (SelectList)ViewBag.Estado, "Selecione", new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12">
                <hr />
            </div>

            <div class="col-md-offset-10">
                <input type="button" class="btn btn-primary" onclick="Back()" value="Cancelar" />
                <input type="submit" class="btn btn-success" value="Alterar" />
            </div>
        </form>
    </div>
</div>

<script src="~/TypeScripts/GlobalScript.js"></script>
<script src="~/TypeScripts/Proprietario/BaseProprietario.js"></script>

src/Senior.Revenda.Mvc/Views/Proprietario/Index.cshtml
@model Senior.Revenda.Contract.DTOs.Filter.ProprietarioFilterDTO
@{
    ViewBag.Title = "Proprietário";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Proprietário <small>Consulta</small></h3>
    </div>
    <div class="panel-body">
        <div class="col-md-6">
            @Html.ActionLink("Cadastrar", "Cadastrar", "Proprietario")
        </div>

        <div class="col-md-12">
            <hr />
        </div>

        <form action="@Url.Content("~/Proprietario/Consultar")" method="get">
            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.Nome, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.Nome, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.Documento, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.Documento, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-12">
                @Html.LabelFor(m => m.Status, new { @class = "col-md-3" })
                <div class="col-md-9">
                    @foreach (var value in Enum.GetValues(Model.Status.GetType()))
                    {
                        <div form-check form-check-inline">
                            @Html.RadioButtonFor(m => m.Status, value, new { @class = "form-check-input" })
                            @Html.Label(value.ToString(), new { @class = "form-check-label" })
                        </div>
                    }
                </div>
            </div>

            <div class="col-md-12">
                <hr />
            </div>

            <div class="col-md-offset-10">
                <input type="submit" class="btn btn-primary" value="Consultar" />
            </div>
        </form>

        @Html.Partial("_ConsultaProprietario", Model)
    </div>
</div>

<script src="~/TypeScripts/Proprietario/Index.js"></script>

src/Senior.Revenda.Mvc/Views/Proprietario/_ConsultaProprietario.cshtml
@model Senior.Revenda.Contract.DTOs.Filter.ProprietarioFilterDTO
@using Senior.Revenda.Contract.Enum

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Lista.Count() > 0)
        {
            foreach (var item in Model.Lista)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Documento)
                    </td>
                    <td>
                        @Html.ActionLink("Alterar", "Alterar", "Proprietario", new { id = item.Id }, null) |
                        @if (item.Status == StatusEnum.Ativo)
                        {
                            <a onclick="CancelarProprietario('@Request.Url.Authority', '@item.Id')">Cancelar</a>
                        }
                        else
                        {
                            <a onclick="AtivarProprietario('@Request.Url.Authority', '@item.Id')">Ativar</a>
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3">Nenhum registro encontrado.</td>
            </tr>
        }
    </tbody>
</table>

src/Senior.Revenda.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Revenda", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Marca", "Index", "Marca")</li>
                    <li>@Html.ActionLink("Proprietário", "Index", "Proprietario")</li>
                    <li>@Html.ActionLink("Veículo", "Index", "Veiculo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Revenda</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Marca")
    @Scripts.Render("~/bundles/Proprietario")
    @Scripts.Render("~/bundles/Veiculo")
    @RenderSection("scripts", required: false)
</body>
</html>

src/Senior.Revenda.Mvc/Views/Veiculo/Index.cshtml
@model Senior.Revenda.Contract.DTOs.Filter.VeiculoFilterDTO
@{
    ViewBag.Title = "Veículo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Veículo <small>Consulta</small></h3>
    </div>
    <div class="panel-body">
        <div class="col-md-6">
            @Html.ActionLink("Cadastrar", "Cadastrar", "Veiculo")
        </div>

        <div class="col-md-12">
            <hr />
        </div>

        <form action="@Url.Content("~/Veiculo/Consultar")" method="get">
            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.Renavam, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.Renavam, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.Modelo, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.Modelo, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.AnoFabricacao, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.AnoFabricacao, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.Quilometragem, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.Quilometragem, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.ValorMinimo, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.ValorMinimo, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.ValorMaximo, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.ValorMaximo, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.IdProprietario, new { @class = "col-md-3" })
                @Html.TextBoxFor(m => m.IdProprietario, new { @class = "form-control col-md-9" })
            </div>

            <div class="col-md-6 form-group">
                @Html.LabelFor(m => m.IdMarca, new { @class = "col-md-3" })
                @Html.DropDownListFor(m => m.IdMarca, (SelectList)ViewBag.Marca, "Selecione", new { @class = "form-control col-md-10" })
            </div>

            <div class="col-md-12">
                @Html.LabelFor(m => m.Status, new { @class = "col-md-3" })
                <div class="col-md-9">
                    @foreach (var value in Enum.GetValues(Model.Status.GetType()))
                    {
                        <div form-check form-check-inline">
                            @Html.RadioButtonFor(m => m.Status, value, new { @class = "form-check-input" })
                            @Html.Label(value.ToString(), new { @class = "form-check-label" })
                        </div>
                    }
                </div>
            </div>

            <div class="col-md-12">
                <hr />
            </div>

            <div class="col-md-offset-10">
                <input type="submit" class="btn btn-primary" value="Consultar" />
            </div>
        </form>

        @Html.Partial("_ConsultaVeiculo", Model)
    </div>
</div>

<script src="~/TypeScripts/Veiculo/Index.js"></script>

src/Senior.Revenda.Mvc/Views/Veiculo/_ConsultaVeiculo.cshtml
@model Senior.Revenda.Contract.DTOs.Filter.VeiculoFilterDTO
@using Senior.Revenda.Contract.Enum

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Renavam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Lista.Count() > 0)
        {
            foreach (var item in Model.Lista)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Renavam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Modelo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.ActionLink("Alterar", "Alterar", "Veiculo", new { id = item.Id }, null)
                        @if (item.Status == StatusVeiculoEnum.Disponivel)
                        {
                            <span>| </span><a onclick="VenderVeiculo('@Request.Url.Authority', '@item.Id')">Vender</a>
                            <span>| </span><a onclick="IndisponibilizarVeiculo('@Request.Url.Authority', '@item.Id')">Indisponibilizar</a>
                        }
                        else if (item.Status == StatusVeiculoEnum.Vendido)
                        {
                            <span>| </span><a onclick="IndisponibilizarVeiculo('@Request.Url.Authority', '@item.Id')">Indisponibilizar</a>
                        }
                        else if (item.Status == StatusVeiculoEnum.Indisponivel)
                        {
                            <span>| </span><a onclick="VenderVeiculo('@Request.Url.Authority', '@item.Id')">Vender</a>
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="5">Nenhum registro encontrado.</td>
            </tr>
        }
    </tbody>
</table>